### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by astrojuanlu** [shanglun/horuslp#1]
I saw the article about HorusLP on Toptal, super interesting!

However, to actually use this code it would need a license. It is my understanding that, by publishing the code on GitHub, you intend it to be open source, but without the license "all rights are reserved" and users can't do anything with it.

I recommend a permissive license, like MIT or BSD, which allows reuse in closed source as well, but you might want to use something like GPL or AGPL, which mandates that anything using HorusLP be free (as in freedom) software itself. Your call.

Happy to help or provide more details! Sorry for the lack of links, I'm on the phone :)

**Comment by shanglun** [comment]
Hi Juan Luis!

Thanks for letting me know! I thought I chose GPL but will figure this out - I wanted to make it MIT for certain classes of users like academics, startups, and nonprofits and probably got didn't do it right. Will figure this out and ping back :)

**Comment by shanglun** [comment]
All right, the license has been added. Let me know if you have any questions want to discuss further 😄

**Comment by astrojuanlu** [comment]
LGPLv3, fair enough :) Thanks and closing!
